### ISSUE TITLE
AEP-1 - Signup API for Student and Teacher

### ISSUE THREAD

**Issue by sugandhitushar** [sugandhitushar/assignment-evalutation-portal#1]
Create a signup API for student and teacher. Below is the API structure - 

1. Create Student API - 

POST /v1/student/signup
Request body - 
{
	"firstName": String (Mandatory),
	"lastLame": String (Mandatory),
	"email": String (Mandatory),
	"phoneNo": String (Mandatory),
	"password": String (Mandatory),
	"avatarUrl": String (Optional),
	"gender": String (Mandatory),
	"collegeFileNumber": String (Optional),
	"permanentRegistrationNumber": String (Optional),
	"admissionDate": Date (Optional),
	"divisionId": Long (Mandatory)
}

Repsonse - 
Status - 201 (Created)
{
	"id": String,
	"firstName": String,
	"lastName": String,
	"email": String,
	"phoneNo": String,
	"avatarUrl": String,
	"gender": String,
	"collegeFileNumber": String,
	"permanentRegistrationNumber": String,
	"admissionDate": Date,
	"divisionId": Long
}

2. Create Teacher API - 

POST /v1/teacher/signup
Request body - 
{
	"firstName": String (Mandatory),
	"lastName": String (Mandatory),
	"email": String (Mandatory),
	"phoneNo": String (Mandatory),
	"password": String (Mandatory),
	"avatarUrl": String (Optional),
	"gender": String (Mandatory),
	"employeeId": String (Mandatory),
	"designation": String (Mandatory),
	"joiningDate": Date (Optional)
}

Repsonse - 
Status - 201 (Created)
{
	"id": String,
	"firstName": String,
	"lastName": String,
	"email": String,
	"phoneNo": String,
	"avatarUrl": String,
	"gender": String,
	"employeeId": String,
	"designation": String,
	"joiningDate": Date
}

**Comment by Shubhaankar** [comment]
merged with master
